config/routes.rb
Rails.application.routes.draw do
  get 'user/new'
  get 'welcome/index'
  resources :articles

  get '/signup', to: 'users#new'
  resources :users, except: [:new]

  root 'welcome#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  self.per_page = 5
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, :through => :article_categories

  validates :title, presence: true, length: {minimum: 4, maximum: 25}
  validates :body, presence: true, length: {minimum: 4, maximum: 144}
  
  #   def self.search(search)
  #   	if search
	 #     	where("title LIKE ?", "%#{search}%")
		# else
		# 	Article.all
		# end
  #   end

end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
	belongs_to :article
	belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, length: {minimum: 3, maximum: 25}
    validates_uniqueness_of :name

    has_many :article_categories
    has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :articles, dependent: :destroy
    validates :username, uniqueness: { case_sensitive: false }, 
                        presence: true, 
                        length: { minimun: 3, maximum: 25 }

        # Regex for email validation 
    # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, uniqueness: { case_sensitive: false }, 
                    presence: true, 
                    length: { maximum: 105 },
                    format: { with: URI::MailTo::EMAIL_REGEXP } #Simple version hehe

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]      
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:alert] = "You must login first!!!"
            redirect_to login_path
        end
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def index
        @articles = Article.paginate(page: params[:page]).where(nil)
        @articles = Article.where("title ILIKE ?", "%#{params[:title]}%").paginate(page: params[:page]) if params[:title].present?
        @articles = Article.where("body ILIKE ?", "%#{params[:body]}%").paginate(page: params[:page]) if params[:body].present?
        @articles = Article.where("title ILIKE ?", "%#{params[:title]}%").where("body ILIKE ?", "%#{params[:body]}%").paginate(page: params[:page]) if params[:title].present? && params[:body].present?
    end

    def show
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:notice] = "Article was succesfully created!!"
            redirect_to @article
        else   
            render :new
        end
    end

    def edit
    end

    def update
        if @article.update(article_params)
            flash[:notice] = "Article was updated succesfully"
            redirect_to @article
        else
            render 'edit'
        end
    end

    def destroy
        if @article.destroy
            flash[:notice] = "Article was Deleted succesfully"
            redirect_to articles_path
        end
    end

    private

        def article_params
            params.require(:article).permit(:title, :body, category_ids: [])
        end

        def set_article
            @article = Article.find(params[:id])
        end

        def require_same_user
            if current_user != @article.user && !current_user.admin?
                flash[:alert] = "You can only edit or delete your own article!!"
                redirect_to @article
            end
        end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index, :show]

    def index
        @categories = Category.paginate(page: params[:page]) 
    end

    def show
        @category = Category.find(params[:id])
        @articles = @category.articles.paginate(page: params[:page])
    end

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Category was successfully created"
            redirect_to @category
        else
            render :new
        end
    end

    def edit
        @category = Category.find(params[:id])
    end

    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:notice] = "Category was Sucessfully updated!!"
            redirect_to @category
        else
            render :edit
        end
    end

    private

    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !(logged_in? && current_user.admin?)
            flash[:alert] = "Admin Only can action!!!"
            redirect_to categories_url
        end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Logged in Successfull"
            redirect_to user
        else
            flash.now[:alert] = "There was something wrong with your login detail"
            render :new
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged Out"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]
 

  def index
    # @users = User.order("created_at ASC")
    @users = User.paginate(page: params[:page])

  end
  
  def show
    @articles = set_user.articles.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to MFA-Blog #{@user.username}, you have successfully sign in"
      redirect_to articles_path
    else
      render 'new' # 'new'
    end
  end

  def edit
  end

  def update
    if set_user.update(user_params)
      flash[:notice] = "Your account successfully updated!!!"
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Akun dan semua article nya telah dihapus"
    redirect_to root_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your account!!"
      redirect_to @user
    end 
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
    redirect_to articles_path if logged_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options = { size: 80})
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}}"
        image_tag(gravatar_url, alt: user.username, class: "rounded mx-auto d-block shadow")
    end
end

app/helpers/article_helper.rb
module ArticleHelper
    
end

app/helpers/user_helper.rb
module UserHelper
    
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_articles.html.erb
<div class="container">
    <% @articles.each do |article| %>
        <div class="row justify-content-center">
        <div class="col-8 mt-4">
            <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
                <% if article.user %>
                    by <%= link_to article.user.username, user_path(article.user) %>    
                <% end %>
                <% if article.categories.any? %>
                    <div class="mt-2">
                        <%= render article.categories %>
                    </div>
                <% end %>            
            </div>
            <div class="card-body">
                <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
                <p class="card-text"><%= truncate(article.body, length: 100) %></p>
                <%= link_to 'View', article_path(article), class: "btn btn-outline-success"%>
                <% if logged_in? && (article.user == current_user || current_user.admin?) %>
                    <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-warning"%>
                    <%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "are you sure?"}, class: "btn btn-outline-danger" %>   
                <% end %>
            </div>
            <div class="card-footer text-muted">
                <small>Created <%= time_ago_in_words(article.created_at) %> ago,
                edited <%= time_ago_in_words(article.updated_at) %> ago, </small>
            </div>
            </div>
        </div>
        </div>
    <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render 'shared/errors', obj: @article %>
            <%= form_with model: @article, class: "shadow p-3 mb-4 bg-info rounded", local: true do |f| %>
                <div class="form-group row">
                    <%= f.label :title, class: "col-sm-2 col-form-label text-light" %> 
                    <div class="col-sm-10">
                        <%= f.text_field :title, class: "form-control", placeholder: "Title of Article" %>
                    </div>
                </div>
                <div class="form-group row">
                    <%= f.label :body, class: "col-sm-2 col-form-label text-light"%> 
                    <div class="col-sm-10"> 
                        <%= f.text_area :body, class: "form-control", rows: 7, placeholder: "Description of Article" %>
                    </div>
                </div>
                <div class="form-group row">
                    <%= f.label :category, class: "col-sm-2 col-form-label text-light"%> 
                    <div class="col-sm-10"> 
                        <%= f.collection_select(:category_ids, Category.all, :id, :name, {prompt: "Please select a categories (optional)"}, {:multiple => true, size: 3, class: "custom-select shadow rounded"}) %>
                    </div>
                </div>
                <div class="form-group row justify-content-center">
                    <%= f.submit class: "btn btn-outline-light btn-lg " %>       
                </div>
            <% end %>
            <div class="mb-3 form-group row justify-content-center">
                <%= link_to '[ Return to articles page ]', articles_path, class: "text-info"  %>
            </div>
        </div>
    </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit an Article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">List of Article</h1>

<div class="row justify-content-center">
  <div class="col-6 pt-4">
    <%= form_tag articles_path, method: :get do %>  
      <div class="form-group row ">
        <%= text_field_tag :title, params[:title], placeholder: "Search title", class: "form-control col-lg-4" %>
        <div class="col-sm-2">
          <%= submit_tag "Search", class: "btn btn-primary", name: nil %>
        </div>
        <%= text_field_tag :body, params[:body], placeholder: "Search body", class: "form-control col-lg-4" %>
        <div class="col-sm-2">
          <%= submit_tag "Search", class: "btn btn-primary", name: nil %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="flickr_pagination">
  <%= will_paginate @articles, container: false %>
</div>

<%= render 'articles' %>  

<div class="flickr_pagination">
  <%= will_paginate @articles, container: false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create an Article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.title %></h2>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          by <%= @article.user.username if @article.user %>
          <%= link_to gravatar_for(@article.user, size: 100), user_path(@article.user) %>
          <% if @article.categories.any? %>
            <div class="mt-2">
              <%= render @article.categories %>
            </div>
          <% end %>
        </div>
        <div class="card-body">
          <div class="card-text text-left"><%= simple_format(@article.body) %></div>
          <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
            <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-warning"%>
            <%= link_to 'Delete', article_path(@article), method: :delete,
              data: {confirm: "are you sure?"}, class: "btn btn-outline-danger"%>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(@article.created_at) %> ago,
          edited <%= time_ago_in_words(@article.updated_at) %> ago, </small>
        </div>
      </div>
    </div>
  </div>
  <div class="form-group row justify-content-center">
    <%= link_to '[ Return to articles page ]', articles_path, class: "text-info"  %>
  </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-info mr-1"  %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
<%= form_with model: @category, class: "shadow p-3 mb-4 bg-info rounded", local: true do |f| %>
    <div class="form-group row">
        <%= f.label :name, "Category Name", class: "col-sm-2 col-form-label text-light" %>
        <div class="col-sm-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name of category" %>
        </div>
    </div>

    <div class="form-group row justify-content-center">
        <%= f.submit class: "btn btn-outline-light btn-lg" %>       
    </div>
<% end %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit a Category Name</h1>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <%= render "form" %>
        </div>
    </div>
    <div class="form-group row justify-content-center">
        <%= link_to '[ Return to category show page ]', category_path(@category), class: "text-info"  %>
    </div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>
<div class="flickr_pagination">
	<%= will_paginate @categories,container: false %>
</div>	
<div class="container">
    <% @categories.each do |category| %>
        <div class="row justify-content-center">
	        <div class="col-4 mt-4">
	            <div class="card text-center shadow mb-5 bg-white rounded">
		            <div class="card-body">
		                <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
						<p class="card-text"><%= pluralize(category.articles.count, "Article") %></p>
		            </div>
		            <div class="card-footer text-muted">
		                <small>Created <%= time_ago_in_words(category.created_at) %> ago,
		                edited <%= time_ago_in_words(category.updated_at) %> ago, </small>
		            </div>
	            </div>
	        </div>
        </div>
    <% end %>
</div>
<div class="flickr_pagination">
	<%= will_paginate @categories,container: false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create a New Category</h1>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <%= render 'shared/errors', obj: @category %>
            <%= form_with model: @category, class: "shadow p-3 mb-4 bg-info rounded", local: true do |f| %>
                <div class="form-group row">
                    <%= f.label :name, "Category Name", class: "col-sm-2 col-form-label text-light" %>
                    <div class="col-sm-10">
                        <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name of category" %>
                    </div>
                </div>

                <div class="form-group row justify-content-center">
                    <%= f.submit class: "btn btn-outline-light btn-lg" %>       
                </div>
            <% end %>
            
        </div>
    </div>
</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>

<% if logged_in? and current_user.admin? %>
  <div class="text-center mt-4">
    <%= link_to "Edit Category", edit_category_path(@category), class: "btn btn-outline-warning"  %>
  </div>
<% end %>

<h3 class="text-center mt-4">Articles</h3>

<div class="flickr_pagination mt-4">
  <%= will_paginate @articles, container: false %>
</div>

<%= render 'articles/articles' %>

<div class="flickr_pagination mt-4">
  <%= will_paginate @articles, container: false %>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
	<div class="container text-center">
		<small>Copyright &copy; <%= link_to "Faiz Alam", "https://github.com/mfaiza", class: "text-white" %></small>
	</div>
</footer>

app/views/layouts/_messages.html.erb
<style>

</style>
<div class="container">
	<% flash.each do |name, msg| %> 
		<div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
			<%= msg %>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
			</button>
		</div>
	<% end %> 	
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "ArizuBlog", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <%= link_to 'Bloggers', users_path, class: "nav-link" %>
            </li>
            <!-- Articles -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Articles
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <% if logged_in? %>
                    <%= link_to "Create a new article", new_article_path, class: "dropdown-item" %>
                <% end %>
                    <%= link_to "View the article", articles_path, class: "dropdown-item"  %>
                </div>
            </li>
            <!-- Categories -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Categories
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <% if logged_in? && current_user.admin? %>
                    <%= link_to "Create a new categories", new_category_path, class: "dropdown-item" %>
                <% end %>
                    <%= link_to "View the Categories", categories_path, class: "dropdown-item"  %>
                </div>
            </li>
            <!-- Profile/Sign inout -->
            <% if logged_in? %>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
                        <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
                        <div class="dropdown-divider"></div>
                        <b><%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: {confirm: "Are you sure?"} %></b>
                    </div>
                </li>
                <li class="nav-item">   
                    <%= link_to "Log Out", logout_path, class: "nav-link", method: :delete  %>
                </li>
            <% else %>
                <li class="nav-item">
                    <%= link_to "Log In", login_path, class: "nav-link"  %>
                </li>
                <li class="nav-item">
                    <%= link_to "Sign Up", signup_path, class: "nav-link"  %>
                </li>
            <% end %>
        </ul>
        
        <%= form_tag articles_path, class: "form-inline my-2 my-lg-0", method: :get do %>
            <%= search_field_tag :search, params[:search], class: "form-control mr-sm-2", placeholder: "Search" %>  
            <%= submit_tag "Search", class: "btn btn-outline-primary my-2 my-sm-0", name: nil %>
        <% end %>
        
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>ArizuBlog</title>
    <%= favicon_link_tag 'icon.png' %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column ">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>  
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h2 class="alert-heading"><%= obj.errors.count %> Errors Detected from <%= obj.class.name.downcase %>: </h2>
        <ul>
            <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <%= render 'shared/errors', obj: @user %>
            <%= form_with model: @user, class: "shadow p-3 mb-4 bg-info rounded", local: true do |f| %>
                <div class="form-group row">
                    <%= f.label :username, class: "col-sm-2 col-form-label text-light" %>
                    <div class="col-sm-10">
                        <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a Username" %>
                    </div>
                </div>
                <div class="form-group row">
                    <%= f.label :email, class: "col-sm-2 col-form-label text-light"%> 
                    <div class="col-sm-10"> 
                        <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your Email" %>
                    </div>
                </div>
                <div class="form-group row">
                    <%= f.label :password, class: "col-sm-2 col-form-label text-light"%> 
                    <div class="col-sm-10"> 
                        <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Enter your Password" %>
                    </div>
                </div>
                <div class="form-group row justify-content-center">
                    <%= f.submit(@user.new_record? ? "Sign Up" : "Update account", class: "btn btn-outline-light btn-lg ") %>       
                </div>
            <% end %>
            <% if logged_in? %>
                <div class="mb-3 form-group row justify-content-center">
                    <%= link_to '[ Return to articles page ]', articles_path, class: "text-info"  %>
                </div>
            <% else %>
                <div class="mb-3 form-group row justify-content-center">
                    <%= link_to '[ Return to Home page ]', root_path, class: "text-info"  %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">MFA-Blog Bloggers</h1>
<div class="flickr_pagination">
  <%= will_paginate @users, container: false %>
</div>
<div class="container">
    <% @users.each do |user| %>
        <div class="row justify-content-center">
        <div class="col-8 mt-4">
            <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
                <%= link_to user.username, user %>
            </div>
            <div class="card-body">
                <h5 class="card-title">
                    <%= gravatar_for(user, size: 150)%>
                </h5>
                <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
                <%= link_to 'View Profile', user_path(user), class: "btn btn-outline-success"%>
                <% if logged_in? %>
                    <% if user == current_user %>
                        <%= link_to 'Edit Profile', edit_user_path(user), class: "btn btn-outline-warning"%>
                    <% end %>
                    <% if current_user.admin? %>
                        <%= link_to 'Delete Profile', user_path(user), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure delete this User Account and all Associated Articles? "}  %>
                    <% end %>
                <% end %>
            </div>
            <div class="card-footer text-muted">
                <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
            </div>
            </div>
        </div>
        </div>
    <% end %>
</div>
<div class="flickr_pagination mb-4">
  <%= will_paginate @users, container: false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign Up</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"> <%= @user.username %>'s profile</h1>

<%= gravatar_for @user, size: 200 %>

<% if logged_in? and @user == current_user %>
  <div class="text-center mt-4">
    <%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-outline-warning"  %>
  </div>
<% end %>

<div class="flickr_pagination mt-4">
  <%= will_paginate @articles, container: false %>
</div>
<h3 class="text-center mt-4">Articles</h3>

<%= render 'articles/articles' %>

<div class="flickr_pagination mt-4">
  <%= will_paginate @articles, container: false %>
</div>

app/views/welcome/index.html.erb
<div class="container" id="home-container">
	<div class="jumbotron text-center text-white">
		<h1 class="display-4">Arizu Blog</h1>
		<p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
		<hr class="my-4">
		<p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
		<%= link_to 'Sign Up', signup_path, class: "btn btn-success"  %>
	</div>
</div>